nodes:
# Node 0
- ip: "localhost"
  port: 32770
  weight: 1
# Node 1
- ip: "localhost"
  port: 32771
  weight: 2
# Node 2
- ip: "localhost"
  port: 32772
  weight: 1

#- ip: "localhost"
#  port: 32773
#  weight: 1
#- ip: "localhost"
#  port: 32774
#  weight: 1
#- ip: "localhost"
#  port: 32775
#  weight: 1